Repository COSC-499-EquiFood-B/EquiFoodApp-B, pull requests merged in 2023-03, with the labels that each got.

#329 alert arranged
  lib/register/createAdminUser.dart
  lib/register/createUser.dart
Labels: task

#330 sign in and restorant changed
  lib/login/login_widget.dart
  lib/register/createRestaurantUser.dart
Labels: task

#337 Updated approveordeny frontend and backend.
  lib/admin/adminpage.dart
  lib/admin/approveordeny.dart
Labels: task

#347 git action set up
  .github/workflows/flutter-drive.yml
Labels: task

#348 Some progress on approvedpage
  lib/admin/adminpage.dart
  lib/admin/approvedrestaurants.dart
  lib/admin/getApprovedRestaurants.dart
  lib/admin/getUnapprovedRestaurants.dart
Labels: task

#349 action update
  .github/workflows/flutter-drive.yml
  .github/workflows/tests.yml
Labels: documentation, task

#352 progress
  .github/workflows/tests.yml
Labels: documentation, task

#358 Minor styling fixes
  lib/admin/adminpage.dart
  lib/restaurant_dashboard/restaurantSettings.dart
Labels: task

#360 Update createRestaurantUser.dart
  lib/register/createRestaurantUser.dart
Labels: task

#377 sign out alert added
  lib/admin/adminpage.dart
  lib/pickup_map/pickup_map_widget.dart
  lib/statspages/statisticsforindiv.dart
Labels: invalid

#383 Update restaurant appbars
  lib/restaurant_dashboard/createDonation.dart
  lib/restaurant_dashboard/restaurant_dashboard_widget_2.dart
  lib/statspages/statisticsforresto.dart
Labels: task

#386 action testing
  .github/workflows/test2.yml
Labels: task

#388 387 UI changes restaurant user
  lib/restaurant_dashboard/createDonation.dart
  lib/restaurant_dashboard/donationCard.dart
  lib/restaurant_dashboard/editDonation.dart
  lib/restaurant_dashboard/restaurant_dashboard_widget_2.dart
Labels: enhancement, task

#390 389 streambuilder indiv dashboard
  lib/confirmation/confirmation.dart
  lib/indiv_dashboard/getDonations.dart
  lib/indiv_dashboard/indivDashboard.dart
  lib/indiv_item/indiv_item_widget.dart
  lib/main.dart
Labels: enhancement, task

#398 time works
  lib/confirmation/confirmation.dart
  pubspec.lock
  pubspec.yaml
Labels: task

#401 replaced FutureBuilder with StreamBuilder on ApprovedRestaurantsPage
  lib/admin/adminpage.dart
  lib/admin/approvedrestaurants.dart
  lib/admin/getApprovedRestaurants.dart
  lib/admin/getUnapprovedRestaurants.dart
Labels: enhancement, task

#405 update
  lib/login/login_widget.dart
  lib/register/createAdminUser.dart
  lib/register/createUser.dart
Labels: task

#407 403 remove unused import
  lib/register/createAdminUser.dart
  lib/register/createRestaurantUser.dart
  lib/register/createUser.dart
  lib/restaurant_dashboard/donationCard.dart
  lib/restaurant_dashboard/editDonation.dart
  lib/restaurant_dashboard/getDonationsData.dart
  lib/restaurant_dashboard/restaurant_dashboard_widget_2.dart
  lib/restaurant_dashboard/unapprovedUser.dart
  lib/settings_page/profile_page.dart
  lib/settings_page/settings.dart
  lib/statspages/statisticsforadmin.dart
  lib/utils/displayAlert.dart
  test/widget_test.dart
Labels: task

#408 403 remove unused import
  lib/admin/adminpage.dart
  lib/admin/approvalpage.dart
  lib/admin/approvedrestaurants.dart
  lib/admin/deniedpage.dart
  lib/admin/getApprovedRestaurants.dart
  lib/admin/getUnapprovedRestaurants.dart
  lib/auth/auth_util.dart
  lib/backend/backend.dart
  lib/backend/schema/structs/collection_struct.dart
  lib/backend/schema/user_record.dart
  lib/confirmation/confirmation.dart
  lib/flutter_flow/flutter_flow_util.dart
  lib/flutter_flow/nav/nav.dart
  lib/flutter_flow/upload_media.dart
  lib/indiv_dashboard/default-stats.dart
  lib/indiv_dashboard/getReservedOrders.dart
  lib/indiv_item/indiv_item_widget.dart
  lib/login/login_widget.dart
Labels: task

#410 Update confirmation.dart
  lib/confirmation/confirmation.dart
Labels: task

#412 403 remove unused import
  lib/admin/approveordeny.dart
  lib/restaurant_dashboard/getDonationsData.dart
Labels: task

#413 Update confirmation.dart
  lib/confirmation/confirmation.dart
Labels: task

#414 Update confirmation.dart
  lib/confirmation/confirmation.dart
Labels: task
